### ISSUE TITLE
Firefox, иконка на тёмной теме

### ISSUE THREAD

**Issue by Nidrop** [PlayShikimoriApp/PlayShikiApp#1]
На тёмной теме не видно иконки расширения.
![image](https://user-images.githubusercontent.com/38117732/59704900-e1a9bc80-9205-11e9-9025-fdc1bf08f5ce.png)

**Comment by ChronoMonochrome** [comment]
Ок, подумаю над решением, если Firefox в принципе позволяет иметь расширениям несколько иконок, это должно быть разрешимо.

**Comment by Nidrop** [comment]
А разве недостаточно сделать универсальную иконку? Ведь темная тема и в хроме есть. Поменять тон, сделать обводку, на крайняк вообще фон можно сделать

**Comment by ChronoMonochrome** [comment]
> А разве недостаточно сделать универсальную иконку? Ведь темная тема и в хроме есть. Поменять тон, сделать обводку, на крайняк вообще фон можно сделать

Да, такой вариант тоже рассматриваю. Как доберусь до редактора изображений, посмотрю, что окажется проще.
